FROM mcr.microsoft.com/playwright:v1.40.0-jammy

WORKDIR /app
COPY package.json .
RUN npm install
COPY scraper.js .

ENV SUPABASE_URL=""
ENV SUPABASE_ANON_KEY=""
ENV WORKER_NAME="docker-worker-1"

CMD ["node", "scraper.js"]
